### PR TITLE
bump Go version to 1.12 #trivial

### PR DESCRIPTION
**Pull request by samsalisbury**

### CODE REVIEW

**Comment by sous-machine-account** [comment]
# LGTM!

No errors, no warnings. :shipit:


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by nyarly** [comment]
Having been out of it for a while, take this with a grain of salt, but what I've seen of 1.12, I'd take this on with caution.

**Comment by samsalisbury** [comment]
> Having been out of it for a while, take this with a grain of salt, but what I've seen of 1.12, I'd take this on with caution.

Could you be more specific @nyarly?

**Comment by lachlanh** [comment]
Just based on 1.12 being 3 days old, may be ok to let this sit for a while before we proceed with it ?

**Comment by samsalisbury** [comment]
Closing in favour of #831 @lachlanh

**Pull request closed without merging**
