### PR TITLE
#trivial added user to newdeploy on the cli

### PR DESCRIPTION
**Pull request by lachlanh**

### CODE REVIEW

**Comment by sous-machine-account** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lachlanh** [comment]
This has been tested now, should be ready to go.

**Comment by JC1738** [comment]
@lachlanh LG, not sure if there is a way to write a unit test for this, otherwise can be tested on the server side.   Also is this stil WIP, Danger warns of merging because of that flag, assumed not since your last email.

**Comment by lachlanh** [comment]
@JC1738 @nyarly can I get this one merged ? danger warning is before I marked it trivial. Not sure how to rerun danger without committing anything ?

**Pull request merged**
