### PR TITLE
Sous deployments command

### PR DESCRIPTION
**Pull request by samsalisbury**
Supersedes #409

### CODE REVIEW

**Comment by sous-machine-account** [comment]
LGTM

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by alrs** [comment]
I've hit what I believe to be a bug in "deployments." If I run "sous deployments" in either the root of the ot-brulee repo or down in the server/ subdirectory I get the same result back. I would expect to not get any result if I wasn't in the server/ directory, which is the configured offset.

**Comment by alrs** [comment]
I'm in a spot where ot-sous-server 0.5.16 has failed to deploy in prod-euwest1, but "sous deployments" is reporting "prod-euwest1 <no flavor> 0.5.16+0.5.14-ef6bd4a-20170615-231650 OK", which is wrong.

**Comment by samsalisbury** [comment]
More erroneous looking output:

```
$ sous deployments
Fetching deployments of github.com/opentable/restaurant-messages-generator-api

Cluster      Flavor Version Status
ci-sf               1.0.571 OK
ci-uswest2          1.0.571 <not deployed>
pp-sf               1.0.571 OK
pp-uswest2          1.0.571 OK
prod-euwest1        1.0.569 OK
prod-ln             1.0.571 actual version deployed: 1.0.569
prod-sc             1.0.571 actual version deployed: 1.0.569
prod-uswest2        1.0.571 actual version deployed: 1.0.569
```

ci-uswest2 is in fact deployed at the correct version, according to singularity.

**Comment by nyarly** [comment]
Closing this as out of date. We should have this command, but it should be based on the /status endpoint

**Pull request closed without merging**
