### PR TITLE
WaitGroup for deployment assembly goroutine. #trivial

### PR DESCRIPTION
**Pull request by alrs**

### CODE REVIEW

**Comment by sous-machine-account** [comment]
LGTM

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by alrs** [comment]
I aim to address
`debug: 2017/06/14 13:29:01 actual_deployment_set.go:156: from = dep from req http://singularity-prod-euwest1.otenv.com err = send on closed channel
debug: 2017/06/14 13:29:01 actual_deployment_set.go:157: debug.Stack() = goroutine 157 [running]:
runtime/debug.Stack(0xc42000f9a0, 0xcded28, 0x14)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/opentable/sous/ext/singularity.catchAndSend(0xc42045a780, 0x36, 0xc420302120)
        /ext-go/1/src/github.com/opentable/sous/ext/singularity/actual_deployment_set.go:157 +0x1cc
panic(0xc04680, 0xc4206edb80)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/opentable/sous/ext/singularity.depPipeline.func1(0xc420302120, 0xc4202f8000, 0x12f3f40, 0xc4204f68a0, 0xc4202fa090, 0xc4203021e0, 0xc42049c9f0, 0x29, 0x12eeee0, 0xc4202fd3c0, ...)
        /ext-go/1/src/github.com/opentable/sous/ext/singularity/actual_deployment_set.go:264 +0x27e
created by github.com/opentable/sous/ext/singularity.depPipeline
        /ext-go/1/src/github.com/opentable/sous/ext/singularity/actual_deployment_set.go:266 +0x2ca`

**Comment by samsalisbury** [comment]
Thanks for looking into this. I know it's WIP, but not sure it's #trivial as it may or may not fix a bug. Isn't #trivial for stuff like tests or documentation that doesn't require a change log? Bugfixes should have an item under the "Fixed" heading I think. Fine to let WIP PRs fail due to lack of changelog though.

**Comment by samsalisbury** [comment]
However I would really like to merge and deploy this, cos it might just work. The WIP label is putting me off doing that... Let's talk about it at standup.

**Comment by alrs** [comment]
This is passing locally. We're looking to solve an outage with a deploy, so we're not waiting on Travis to merge this PR, as this code will all get tested again in a few minutes when we cut a release.

**Comment by samsalisbury** [comment]
Cool, could you expand on the outage just to keep me in the loop? Or do you mean the issue with resolve stuck in `ResolvePendingRequest` in prod-euwest1? @alrs @nyarly

**Pull request merged**
