### PR TITLE
RIP sqlite3 SOUS-899

### PR DESCRIPTION
**Pull request by nyarly**
SQLite removed from the project. Sous now requires Postgres to run server stuff.

### CODE REVIEW

**Comment by sous-machine-account** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Debugging output: +	spew.Dump(str)<br />
 (there may be others)</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR: 225195 lines of code changed</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by samsalisbury** [comment]
Generally looks good; I've fixed issue with test db names (didn't like hyphens from test names) and also broken the client -> postgres dependency. All that's left is some erroneous stdout output that's breaking `sous manifest get` by adding `(string) (len=15) "sslmode=disable"` at the start of output. Wasn't obvious where that was coming from so leaving it here for now.

**Comment by samsalisbury** [comment]
Smoke tests are failing due to above mentioned issue; for completeness I'm seeing this sort of thing:

```
--- FAIL: TestSousDeploy/newdeploy/simple (29.12s)
                testutils_test.go:55: Using sous binary "/Users/ssalisbury/src/github.com/opentable/sous/.smoketest/2018-05-03T16-01-02/sous" (from $SMOKE_TEST_BINARY)
                testutils_test.go:192: Writing test data to "/Users/ssalisbury/src/github.com/opentable/sous/.smoketest/2018-05-03T16-01-02/data/TestSousDeploy/newdeploy/simple" (from $SMOKE_TEST_DATA_DIR)
                testbunchofsousservers_test.go:101: Creating DB for TestSousDeploy/newdeploy/simple called sous_test_sousdeploy_newdeploy_simple_0
                testbunchofsousservers_test.go:101: Creating DB for TestSousDeploy/newdeploy/simple called sous_test_sousdeploy_newdeploy_simple_1
                testbunchofsousservers_test.go:101: Creating DB for TestSousDeploy/newdeploy/simple called sous_test_sousdeploy_newdeploy_simple_2
                newdeploy_test.go:149: Sous version: sous version 0.5.91-38-g09a60f1c-devbuild-2018-05-03T16-01-02 (go1.10.1 darwin/amd64)
                newdeploy_test.go:151: manifest get returned invalid YAML: yaml: line 1: mapping values are not allowed in this context                                
                        Invalid YAML was:                                                                                                                                                                   
                        (string) (len=15) "sslmode=disable"                                                                                     
                        Source: github.com/user1/repo1  
```

**Comment by JC1738** [comment]
@samsalisbury I see the same, smoke tests fail with panic, integration tests seem to fail for a different reason.  cc:/ @nyarly

**Pull request merged**
