### PR TITLE
#WIP Globallogger

### PR DESCRIPTION
**Pull request by JC1738**
Just creating PR so can have TC continual check my commits :)

### CODE REVIEW

**Comment by sous-machine-account** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by JC1738** [comment]
@samsalisbury @nyarly 

PR passes in TC, but fails in travis.  Found the error, but not sure where to go from here:

`
2018/05/09 17:08:28 docker_helpers.go:125: Waiting for Singularity to stabilize
2018/05/09 17:08:28 docker_helpers.go:148: There are 2 pending requests still...
2018/05/09 17:08:30 docker_helpers.go:168: There are 5 pending deploys still...
2018/05/09 17:08:31 docker_helpers.go:168: There are 3 pending deploys still...
2018/05/09 17:08:36 docker_helpers.go:168: There are 1 pending deploys still...
2018/05/09 17:08:41 docker_helpers.go:162: No pending requests or deploys at Singularity
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0xc73b10, 0x16)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:619 +0x81
runtime.sysMap(0xc560e10000, 0x33f80000, 0x906b00, 0x132e538)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1312ca0, 0x33f80000, 0x7db4e6)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x1312ca0, 0x19fbc, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x1312ca0, 0x19fbc, 0x132e548, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x1312ca0, 0x19fbc, 0x101, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x1312ca0, 0x19fbc, 0x2b5013000101, 0xc420402600)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x33f78000, 0x460100, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:1170`

**Comment by JC1738** [comment]
@nyarly is also seeing the memory problem locally, marking it WIP till that is fixed.

**Comment by JC1738** [comment]
I also found another declaration of a global Log that is used in places, need to remove that and continue updating the code.

**Pull request closed without merging**
