### PR TITLE
Fixed problems parsing JSON unmarshalling

### PR DESCRIPTION
**Pull request by nyarly**
When the Singularity API changed, JSON marshalling was breaking our
history entries, which crashed rectifies.

### CODE REVIEW

**Comment by sous-machine-account** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by alrs** [comment]
Ignoring Danger.

**Comment by samsalisbury** [comment]
Surely this should have a "Fixed" changelog entry? cc @nyarly @nyarly

**Comment by samsalisbury** [comment]
OK, just saw the [changelog entry](https://github.com/opentable/sous/blob/master/CHANGELOG.md#0514) for this. Would be helpful to add comment that it was being added elsewhere to avoid me getting sweaty :P

**Pull request merged**
